### PR TITLE
fix bug when serde with unsupported type

### LINKED ISSUE #491: [undefined] serde with a wrapper type for unserded type
```
package issue_test

import (
	"encoding/json"
	"testing"

	"github.com/bytedance/sonic"
	"github.com/davecgh/go-spew/spew"
	"github.com/stretchr/testify/require"
)

type Function = func()

func MockFunc() {

}

type Unable struct {
	Functions []Function
}

type StructWithUnable struct {
	Foo *Unable
}

func TestMarshalWrapperUnable(t *testing.T) {
	// Wrapper a unbale serde type
	tests := []interface{} {
		map[string]*Function{},
		[]Function{},
		struct {
			Foo *Function
		}{},
	}
	for _, v := range(tests) {
		sout, serr := sonic.Marshal(&v)
		jout, jerr := json.Marshal(&v)
		require.Equal(t, serr, jerr, v)
		require.Equal(t, sout, jout, v)
	}
}

 func TestRule(t *testing.T) {
	type Test struct {
		data string
		value interface{}
	}

	tests := []Test{
		Test {
			data: "null",
			value: new([]Function),
		},
		Test {
			data: "[null, null]",
			value: new([]Function),
		},
		Test {
			data: "{\"foo\": null}",
			value: new(struct {
				Foo *Function
			}),
		},
	}
	for _, v := range(tests) {
		spew.Dump(v)
		jerr := json.Unmarshal([]byte(v.data), &v.value)
		require.NoError(t, jerr)
		serr := sonic.Unmarshal([]byte(v.data), &v.value)
		require.NoError(t, serr)
	}
 }
 
```

### LINKED ISSUE #554: issue: nil pointer of struct which has supported-type-fields returns error
## reason
- `*http.Request` has unsupported type fields like `GetBody func() (io.ReadCloser, error)`, but the passed obj is nil, thus `std` think it is a nil pointer and encode it as nothing, while sonic report error when compiling the ptr type
## codes
```
import (
	"encoding/json"
	"net/http"
	"testing"

	"github.com/bytedance/sonic"
	jsoniter "github.com/json-iterator/go"
	"github.com/stretchr/testify/assert"
)

type Context struct {
	*http.Request
}


func TestContext(t *testing.T) {
	var obj = new(Context)
	out, err := sonic.Marshal(obj)
	out1, err1 := jsoniter.Marshal(obj)
	out2, err2 := json.Marshal(obj)
	println(string(out2))
	assert.Equal(t, err2 ==nil, err1 ==nil)
	assert.Equal(t, err2 ==nil, err ==nil)
	assert.Equal(t, out2, out1)
	assert.Equal(t, out2, out)
	// err = sonic.Unmarshal(out, obj)
	// if err != nil {
	// 	t.Fatal(err)
	// }
}
```

## result 
```
--- FAIL: TestContext (0.02s)
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	TestContext
        	Error:      	Not equal: 
        	            	expected: []byte{0x7b, 0x7d}
        	            	actual  : []byte(nil)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,2 @@
        	            	-([]uint8) (len=2) {
        	            	- 00000000  7b 7d                                             |{}|
        	            	-}
        	            	+([]uint8) <nil>
        	            	 
        	Test:       	TestContext
FAIL
```

### PR DESCRIPTION
**Pull request by liuq19**
#### What type of PR is this?

fix

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: 
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

Fixes #491,  Fixes #554

### CODE REVIEW

File: issue_test/issue491_test.go [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+	}
+
+	tests := []Test{
+		 {
+			data: "null",
+			value: new([]Function),
+		},
+		 {
+			data: "[null, null]",
+			value: new([]Function),
```
Comment (AsterDY) [inline issue_test/issue491_test.go:60]: 1和2有啥区别？

**Review by AsterDY — APPROVED** [review]
