### PR TITLE
fix(aarch64): support parse map that key is float

### LINKED ISSUE #747: error issue in arm64 build when unmarshaling map with float keys
**Describe the bug**

Recent migration to multi arch instances(arm64/amd64) caused unmarshalling error in the production. On debugging we got sonic marshalling for string `{"1.4":2.0, "1.45":2.0, "1.5":2.0, "1.55":1.83, "1.6":1.67, "1.65":1.50, "1.7":1.33, "1.75":1.17, "1.8":1.00, "1.85":1.00, "1.9":1.00, "1.95":1.00, "2.0":1.00}` to `map[float32]float32` throws error also some internal issue might be there due to which our tasks got killed because as per handling on our code error is handled gracefully shouldn't lead to task kill. 
**To Reproduce**

Ref code:
```
func Test_getDiscountMultiplierConfig(t *testing.T) {
	// use arm64
	tests := []struct {
		name           string
		config         string
		expectedConfig map[float32]float32
	}{
		{
			name:   "should fetch config when set",
			config: `{"1.2":1.8, "1.25":1.75, "1.3":1.6, "1.35":1.5, "1.4":1.4, "1.45":1.3, "1.5":1.2, "1.55":1.1, "1.6":1.0, "1.65":0.9, "1.7":0.8, "1.75":0.7, "1.8":0.6}`,
			expectedConfig: map[float32]float32{
				1.2:  1.8,
				1.25: 1.75,
				1.3:  1.6,
				1.35: 1.5,
				1.4:  1.4,
				1.45: 1.3,
				1.5:  1.2,
				1.55: 1.1,
				1.6:  1.0,
				1.65: 0.9,
				1.7:  0.8,
				1.75: 0.7,
				1.8:  0.6,
			},
		},
		{
			name:           "should fetch empty config when not set",
			config:         ``,
			expectedConfig: map[float32]float32{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, tp := appconfig.MustNewTestProvider()
			tp.MustSet("feature.discount_multiplier_config", tt.config)

			discountMultiplierRaw := appconfig.GetString(ctx, "feature.discount_multiplier_config")
			var discountMultiplierMap map[float32]float32
			err := util.JSONUnmarshal(ctx, []byte(discountMultiplierRaw), &discountMultiplierMap)
			if err != nil {
				discountMultiplierMap = make(map[float32]float32)
			}

			if !reflect.DeepEqual(discountMultiplierMap, tt.expectedConfig) {
				t.Errorf("getDiscountMultiplierConfig() = %v, want %v", discountMultiplierMap, tt.expectedConfig)
			}
		})
	}
}
```

and to run - `GOARCH=arm64 go test -v ./...`

**Expected behavior**

It should be able to works equivalent across arm/amd env. Preferable it should work with both also this raised a reliability concern in using complex structs with sonic marshalling. Can you please me with some reference doc on eligible structs

**Screenshots**

**Sonic version:**

tried with upgraded version of sonic `v1.12.9`

**Environment:**

The output of `go env`.

**Additional context**

### PR DESCRIPTION
**Pull request by liuq19**
#### What type of PR is this?

fix

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) Translate the PR title into Chinese.
支持JSON 解析为 key 是浮点数的map

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: 
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

Fixed #747

### CODE REVIEW

File: internal/decoder/optdec/map.go [hunk 1]
```diff
@@ -354,26 +353,40 @@ func decodeKeyI16(dec *mapDecoder, raw string, ctx *context) (interface{}, error
...
 
-func decodeKeyJSONUnmarshaler(dec *mapDecoder, raw string, _ *context) (interface{}, error) {
+func decodeKeyTextUnmarshaler(dec *mapDecoder, raw string, ctx *context) (interface{}, error) {
+	key, err := Unquote(raw)
+	if err != nil {
+		return nil, err
+	}
 	ret := reflect.New(dec.mapType.Key.Pack()).Interface()
-	err := ret.(json.Unmarshaler).UnmarshalJSON([]byte(raw))
+	err = ret.(encoding.TextUnmarshaler).UnmarshalText([]byte(key))
```
Comment (AsterDY) [inline internal/decoder/optdec/map.go:362]: 这里为啥要拷贝key？

**Review by AsterDY — APPROVED** [review]
