### PR TITLE
fix(aarch64): avoid using the boundary pointer of an array

### LINKED ISSUE #762: macOS arm64: Unmarshal leads to "runtime: marked free object in span..."
**Describe the bug**

I'm finding that running multiple goroutines that unmarshal structs of a certain form will lead to errors like `runtime: marked free object in span 0x1296f8f80, elemsize=24 freeindex=8 (bad use of unsafe.Pointer? try -d=checkptr)`

**To Reproduce**

This is a self-contained example of the crash I'm getting; both `go run` and `go run -race` give me a crash on my system (macOS 15.3.1; Apple Silicon M2). I couldn't reproduce this crash on x86.

```
package main

import (
	// Uncomment this to see expected behavior.
	// sonic "encoding/json"
	"log"
	"sync"

	"github.com/bytedance/sonic"
)

type MyJs struct {
	Arr [][2]string
}

func main() {
	type parsedStruct struct {
		parsed MyJs
		err    error
	}
	conv := func(buf []byte) parsedStruct {
		var x MyJs
		err := sonic.Unmarshal(buf, &x)
		return parsedStruct{x, err}
	}

	const msg = `{"Arr":[["foo","bar"]]}`
	log.Printf("%#v\n", conv([]byte(msg)))

	var wg sync.WaitGroup
	for range 20 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for range 500_000 {
				conv([]byte(msg))
			}
		}()
	}
	wg.Wait()
	log.Println("wg done")
}
```

**Expected behavior**

I expect the code to run to completion and exit gracefully; for example, using the stdlib `encoding/json` instead, we get:

```
2025/03/04 15:27:23 main.parsedStruct{parsed:main.MyJs{Arr:[][2]string{[2]string{"foo", "bar"}}}, err:error(nil)}
2025/03/04 15:27:36 wg done
```

**Sonic version:**

v1.12.9

**Environment:**

GOARCH='arm64'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOVERSION='go1.23.6'
GOARM64='v8.6,lse,crypto'

Installed via homebrew on macOS 15.3.1.

### PR DESCRIPTION
**Pull request by liuq19**
#### What type of PR is this?

fix

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: 
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

Fixes #762

### CODE REVIEW

File: internal/decoder/optdec/slice.go [hunk 1]
```diff
@@ -82,7 +82,11 @@ func (d *arrayDecoder) FromDom(vp unsafe.Pointer, node Node, ctx *context) error
 	/* zero rest of array */
 	ptr := unsafe.Pointer(uintptr(vp) + uintptr(i)*d.elemType.Size)
 	n := uintptr(d.len-i) * d.elemType.Size
-	rt.ClearMemory(d.elemType, ptr, n)
+
+	/* the boundary pointer may points to another unknown object, so we need to avoid using it */
+	if n != 0 {
```
Comment (AsterDY) [inline internal/decoder/optdec/slice.go:87]: 你这个好像没修复吧，n == 0 时候 ptr仍然是boudary pointer会被扫描到？
