### PR TITLE
fix: bugs when encoding.TextMarshaler key is integer types or nil pointer

### LINKED ISSUE #827: Integer TextMarshaler keys are converted to strings rather than marshaled
**Describe the bug**

When marshaling maps with keys of integer kind implementing TextMarshaler, the keys are converted to strings rather than marshaled by calling the MarshalText methods.

**To Reproduce**

Run the following code:
```go
type ITM int

func (i ITM) MarshalText() ([]byte, error) {
	return []byte("u" + strconv.Itoa(int(i))), nil
}

func main() {
	b, err := sonic.ConfigStd.Marshal(map[ITM]int{1: 1, 2: 2})
	fmt.Println(string(b), err)
}
```
and you will see `{"1":1,"2":2} <nil>` output.

**Expected behavior**

`{"u1":1,"u2":2} <nil>` output as encoding/json's Marshal prioritizes checking for TextMarshaler before converting integer.

Note that on the default config, particularly when `SortMapKeys` is disabled, the behavior becomes correct. 

**Sonic version:**

v1.13.3

**Environment:**

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bimoadityar/.cache/go-build"
GOENV="/home/bimoadityar/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bimoadityar/.go/pkg/mod"
GOOS="linux"
GOPATH="/home/bimoadityar/.go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/bimoadityar/.config/spkit/bin/sdk/go1.17.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/bimoadityar/.config/spkit/bin/sdk/go1.17.13/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.13"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/bimoadityar/Documents/bimo-test-2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1204808054=/tmp/go-build -gno-record-gcc-switches"
```

### LINKED ISSUE #828: Pointer TextMarshaler keys have the MarshalText method called even on nil values
**Describe the bug**

When marshaling maps with keys of pointer kind implementing TextMarshaler, the MarshalText method is always called even if the key value is nil.

**To Reproduce**

Run the following code:
```go
type ITM struct{ s int }

func (i ITM) MarshalText() ([]byte, error) {
	return []byte("u" + strconv.Itoa(i.s)), nil
}

func main() {
	b, err := sonic.ConfigStd.Marshal(map[*ITM]int{nil: 1})
	fmt.Println(string(b), err)
}
```

Then you will get the application panicking for trying to call MarshalText on nil value.
```
panic: value method main.ITM.MarshalText called using nil *ITM pointer

goroutine 1 [running]:
main.(*ITM).MarshalText(0x93d990?)
        <autogenerated>:1 +0x54
github.com/bytedance/sonic/internal/encoder/alg.(*MapIterator).appendConcrete(0x469445?, 0xc00012e400, 0x6976c0?, 0xc000111b58?)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/alg/mapiter.go:124 +0x90
github.com/bytedance/sonic/internal/encoder/alg.(*MapIterator).appendGeneric(0xc000111c70?, 0xc00012e400, 0xc00043d380?, 0x69f5a0?, 0x0?)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/alg/mapiter.go:113 +0x59a
github.com/bytedance/sonic/internal/encoder/alg.(*MapIterator).append(0x68ce20?, 0x0?, 0xc00012e3c0?, 0xc000111d18?)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/alg/mapiter.go:90 +0x8f
github.com/bytedance/sonic/internal/encoder/alg.IteratorStart(0x68ce20, 0xc0003266c0, 0x1)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/alg/mapiter.go:187 +0x105
encode_map[...]int()
        ?:0 +0x15f
github.com/bytedance/sonic/internal/encoder/x86.EncodeTypedPointer(0xc000292d38, 0x68ce20, 0xc00012c968, 0xc000400000, 0x1)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/x86/stbus.go:48 +0x125
github.com/bytedance/sonic/internal/encoder.encodeInto(0xc000292d38, {0x68ce20, 0xc0003266c0}, 0x1)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/encoder.go:221 +0xd7
github.com/bytedance/sonic/internal/encoder.encodeIntoCheckRace(...)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/encode_norace.go:23
github.com/bytedance/sonic/internal/encoder.Encode({0x68ce20, 0xc0003266c0}, 0x1)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/encoder/encoder.go:174 +0x45
github.com/bytedance/sonic.frozenConfig.Marshal(...)
        /home/bimoadityar/.go/pkg/mod/github.com/bytedance/sonic@v1.13.3/sonic.go:101
main.main()
        /home/bimoadityar/Documents/bimo-test-2/cmd/data/main.go:19 +0x73
```

**Expected behavior**

The MarshalText method is not called for nil value, with output `{"":1} <nil>`.

**Sonic version:**

v1.13.3

**Environment:**

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bimoadityar/.cache/go-build"
GOENV="/home/bimoadityar/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bimoadityar/.go/pkg/mod"
GOOS="linux"
GOPATH="/home/bimoadityar/.go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/bimoadityar/.config/spkit/bin/sdk/go1.17.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/bimoadityar/.config/spkit/bin/sdk/go1.17.13/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.13"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/bimoadityar/Documents/bimo-test-2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1204808054=/tmp/go-build -gno-record-gcc-switches"
```

### PR DESCRIPTION
**Pull request by liuq19**
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: 
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

Fix #827, Fix #828

### CODE REVIEW

**Comment by liuq19** [comment]
bugbot run

**Comment by liuq19** [comment]
@cursor review

File: internal/encoder/alg/mapiter.go [hunk 1]
```diff
@@ -84,15 +84,20 @@ func (self *MapIterator) data() (p []_MapPair) {
 func (self *MapIterator) append(t *rt.GoType, k unsafe.Pointer, v unsafe.Pointer) (err error) {
     p := self.add()
     p.v = v
+    tk := t.Kind()
 
-    /* check for strings */
-    if tk := t.Kind(); tk != reflect.String {
-        return self.appendGeneric(p, t, tk, k)
+    /* check for string */
+    if tk == reflect.String {
```
Comment (AsterDY) [inline internal/encoder/alg/mapiter.go:90]: 如果是 string kind 但是实现了 TextMarshaler 还是有bug吧。比如：
```
type String string

func (s String) MarshalText() ([]byte, error) {
	return []byte("str" + string(s)), nil
}

sonic.ConfigStd.Marshal(map[String]int{"1": 1, "2": 2})
```

**Review by AsterDY — CHANGES_REQUESTED** [review]

File: internal/encoder/alg/mapiter.go (hunk 1 above)
Comment (liuq19) [reply internal/encoder/alg/mapiter.go:90]: golang's implemention is also checking String at first.

https://github.com/golang/go/blob/a62f72f7a7ee606c803d1c68cadd24e45eea5e83/src/encoding/json/encode.go#L990

**Review by AsterDY — APPROVED** [review]
