### PR TITLE
fix bug when parsing into nil iface type

### LINKED ISSUE #772: JIT skip unmatched type bug
**Describe the bug**

should skip unmatched iface type errors

**To Reproduce**

```
package issue_test

import (
	"testing"

	"github.com/bytedance/sonic"
)


func TestIssue758_UnmarshalIntoAnyPointer(t *testing.T) {
	for _, cas := range []unmTestCase {
		{
			name: "nil iface type as struct field",
			data: []byte(`{"id": {"id": "2"},"name": "name"}`),
			newfn: func() interface{} {
				obj := WrapperEface {
				}
				obj.Id = (*fooEface)(nil)
				return &obj
			},
		},
	} {
		t.Run(cas.name, func(t *testing.T) {
			assertUnmarshal(t, sonic.ConfigDefault, cas, true)
		})
	}
}

type WrapperEface struct {
	Name string `json:"name"`
	Id MockEface `json:"id"`
}

type MockEface interface {
	MyMock()
}

type fooEface struct {
	Id *string `json:"id"`
}

func (self *fooEface) MyMock() {

}

type fooEface3 struct {
	Id *string `json:"id"`
}

func (self fooEface3) MyMock() {

}

```

**Expected behavior**

**Screenshots**

```
=== RUN   TestIssue758_UnmarshalIntoAnyPointer/nil_iface_type_as_struct_field
    common_test.go:36: 
            Error Trace:    /data01/home/liuq/sonic/issue_test/common_test.go:36
                                        /data01/home/liuq/sonic/issue_test/issue758_test.go:24
            Error:          Not equal: 
                            expected: &issue_test.WrapperEface{Name:"name", Id:(*issue_test.fooEface)(nil)}
                            actual  : &issue_test.WrapperEface{Name:"", Id:(*issue_test.fooEface)(nil)}
                        
                            Diff:
                            --- Expected
                            +++ Actual
                            @@ -1,3 +1,3 @@
                             (*issue_test.WrapperEface)({
                            - Name: (string) (len=4) "name",
                            + Name: (string) "",
                              Id: (*issue_test.fooEface)(<nil>)
            Test:           TestIssue758_UnmarshalIntoAnyPointer/nil_iface_type_as_struct_field
            Messages:       (*issue_test.WrapperEface)(0xc000524040)({
                             Name: (string) (len=4) "name",
                             Id: (*issue_test.fooEface)(<nil>)
                            })
                            (*issue_test.WrapperEface)(0xc000524020)({
                             Name: (string) "",
                             Id: (*issue_test.fooEface)(<nil>)
                            })
(*issue_test.WrapperEface)(0xc000524020)({
 Name: (string) "",
 Id: (*issue_test.fooEface)(<nil>)
})
(*json.UnmarshalTypeError)(0xc0002e2140)(json: cannot unmarshal  into Go value of type issue_test.MockEface)
(*json.UnmarshalTypeError)(0xc00079a000)(json: cannot unmarshal object into Go struct field WrapperEface.id of type issue_test.MockEface)
```

**Sonic version:**

Please provide the version of Sonic you are using.

**Environment:**

The output of `go env`.

**Additional context**

### LINKED ISSUE #774: Unmarshal decodes empty string ("") into nil for *[]byte, should be []byte{}
**Describe the bug**

When unmarshaling a JSON string value ("") into a *[]byte field, sonic.Unmarshal produces nil instead of an empty byte slice ([]byte{}).

**To Reproduce**

```golang
func TestSonic(t *testing.T) {
	var dest struct {
		ByteArr *[]byte
	}

	err := sonic.Unmarshal([]byte(`{"ByteArr": ""}`), &dest)
	require.NoError(t, err)

	require.Equal(t, *dest.ByteArr, []byte("")) //*dest.ByteArr is []byte(nil), but it should be []byte{}
}
```

**Expected behavior**

"" should be unmarshaled into []byte{} (a non-nil, zero-length slice), not nil. This is how encoding/json behaves.

**Sonic version:**

v1.13.1

### PR DESCRIPTION
**Pull request by liuq19**
#### What type of PR is this?

fix
#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: 
zh(optional): 

Main Changes as the commit order:
1. Fix the bug when parsing `null`  into non-indirected interface value, (TODO: the jit parts is still hard to fix)
2. Fix #774, parse `"` as empty []byte
3. Fix #772, when found the nil iface type, will skip the json value and still parse the remaining fields as encoding/json

#### (Optional) Which issue(s) this PR fixes:

Fixes #772  Fixes #774

### CODE REVIEW

File: issue_test/issue379_test.go [hunk 1]
```diff
@@ -59,32 +59,26 @@ func TestIssue379(t *testing.T) {
...
-        {
-            data: `null`,
-            newf:  func() interface{} { ptr := &Foo{}; return &ptr },
-            equal: func(exp, act interface{}) bool {
-                isExpNil := exp == nil || *(exp.(**Foo)) == nil 
-                isActNil := act == nil || *(act.(**Foo)) == nil 
-                return isActNil == isExpNil
-            },
-        },
+
```
Comment (AsterDY) [inline issue_test/issue379_test.go:62]: 这里为啥删除？

**Review by AsterDY — APPROVED** [review]
