### PR TITLE
fix: trim the trailing whitespace for raw json value

### LINKED ISSUE #805: 传递给UnmarshalJSON的入参，特定情况下，不是一个标准的jsontoken
**传递给UnmarshalJSON的入参，特定情况下，不是一个标准的jsontoken**
格式化的json串，比如：
{
  "d": 12312312
}
最终传入 UnmarshalJSON 时，携带了换行符 \n，导致 UnmarshalJSON 不能按预期执行，最终反序列化失败；
正常的一个 jsontoken 不应该包含 \n;

**Expected behavior**
传入 UnmarshalJSON 应该总是一个合法的 jsontoken；

**Screenshots**
此处的 decimal 是 github.com/shopspring/decimal

示例json串：
Image

UnmarshalJSON入参，可以看到存在换行符，这不是一个合法的 jsontoken；
Image

**Sonic version:**

最新版v1.13.3仍有问题

**Environment:**
GO111MODULE='on'
GOARCH='arm64'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOVERSION='go1.23.9'

### PR DESCRIPTION
**Pull request by liuq19**
#### What type of PR is this?

Fix
#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:  remove the trailing whitespace, to make the `Unmarshaler`'s arg always be a clean json value
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

Fixes #805

### CODE REVIEW

File: issue_test/issue805_test.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+* limitations under the License.
+*/
+
+package issue_test
+
+import (
+	"encoding/json"
+	"testing"
+
+	"github.com/shopspring/decimal"
```
Comment (AsterDY) [inline issue_test/issue805_test.go:23]: 没必要引入一个第三方库吧。。
