### PR TITLE
fix:(encoder) handle map like pointer when calling `call_marshaler_v`

### LINKED ISSUE #258: Panic on map traversal in custom MarshalJSON method using a value receiver
The following code causes a panic on the range operation in the MarshalJSON method. However, it doesn't panic if change the receiver to a pointer type `func (m *Map) MarshalJSON() ([]byte, error)`
```go
type Map map[string]int

func (m Map) MarshalJSON() ([]byte, error) {
	for range m {
	}
	return []byte(`null`), nil
}

func TestMapPanic(t *testing.T) {
	m := Map{
		"one": 1,
	}
	sonic.Marshal(m)
}
```

```
=== RUN   TestMapFailures
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x1060cdf]

goroutine 20 [running]:
runtime.throw({0x129032a?, 0x1013a86?})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:992 +0x71 fp=0xc0000d9b30 sp=0xc0000d9b00 pc=0x1034071
runtime.sigpanic()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/signal_unix.go:825 +0x305 fp=0xc0000d9b80 sp=0xc0000d9b30 pc=0x1048885
aeshashbody()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc0000d9b88 sp=0xc0000d9b80 pc=0x1060cdf
runtime.mapiternext(0xc0000d9c30)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/map.go:934 +0x2cb fp=0xc0000d9bf8 sp=0xc0000d9b88 pc=0x100f30b
runtime.mapiterinit(0xc0000d9c38?, 0x1065a0a?, 0x100cb34?)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/map.go:861 +0x228 fp=0xc0000d9c18 sp=0xc0000d9bf8 pc=0x100efe8
github.com/deliveroo/rs-menus-api.Map.MarshalJSON(0x8834b13?)
	(...)/map_test.go:12 +0x47 fp=0xc0000d9ca0 sp=0xc0000d9c18 pc=0x1248647
github.com/bytedance/sonic/encoder.encodeJsonMarshaler(0xc0000b8420, {0x15b80c8?, 0xc00008e868?}, 0x0)
	(...)/vendor/github.com/bytedance/sonic/encoder/primitives.go:83 +0x42 fp=0xc0000d9d28 sp=0xc0000d9ca0 pc=0x11f99a2
runtime.__json_encoder_15f5000()
	?:0 +0xa3 fp=0xc0000d9db8 sp=0xc0000d9d28 pc=0x15f50a3
github.com/bytedance/sonic/encoder.encodeTypedPointer(0xc0000b8420, 0x1269d80, 0xc00008e868, 0x101c00003f670?, 0x8c727f0?)
	(...)/vendor/github.com/bytedance/sonic/encoder/primitives.go:78 +0x153 fp=0xc0000d9e20 sp=0xc0000d9db8 pc=0x11f98f3
github.com/bytedance/sonic/encoder.EncodeInto(0xc0000b8420, {0x1269d80, 0xc0000a2f60}, 0x0)
	(...)/vendor/github.com/bytedance/sonic/encoder/encoder.go:168 +0xf1 fp=0xc0000d9eb8 sp=0xc0000d9e20 pc=0x11f7911
github.com/bytedance/sonic/encoder.Encode({0x1269d80, 0xc0000a2f60}, 0x0)
	(...)/vendor/github.com/bytedance/sonic/encoder/encoder.go:142 +0xc5 fp=0xc0000d9f10 sp=0xc0000d9eb8 pc=0x11f76e5
github.com/bytedance/sonic.(*frozenConfig).Marshal(0x1269d80?, {0x1269d80?, 0xc0000a2f60?})
	(...)/vendor/github.com/bytedance/sonic/sonic.go:93 +0x30 fp=0xc0000d9f38 sp=0xc0000d9f10 pc=0x12482b0
github.com/bytedance/sonic.Marshal(...)
	(...)/vendor/github.com/bytedance/sonic/api.go:109
github.com/deliveroo/rs-menus-api.TestMapFailures(0x0?)
	(...)/map_test.go:21 +0x67 fp=0xc0000d9f70 sp=0xc0000d9f38 pc=0x1248707
testing.tRunner(0xc000083860, 0x12a7020)
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1439 +0x102 fp=0xc0000d9fc0 sp=0xc0000d9f70 pc=0x10bc942
testing.(*T).Run.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1486 +0x2a fp=0xc0000d9fe0 sp=0xc0000d9fc0 pc=0x10bd7ea
runtime.goexit()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000d9fe8 sp=0xc0000d9fe0 pc=0x10637c1
created by testing.(*T).Run
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1486 +0x35f

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000836c0, {0x1298559?, 0x8768b7ff36af?}, 0x12a7020)
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc0000a2f30?)
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc0000836c0, 0xc00017fcd8)
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1439 +0x102
testing.runTests(0xc000139b80?, {0x143a490, 0x1, 0x1}, {0x15345b8?, 0x40?, 0x0?})
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc000139b80)
	/usr/local/Cellar/go/1.18.3/libexec/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:47 +0x1aa
```

Go version: 1.18.3
Arch: amd64
OS: darwin

### PR DESCRIPTION
**Pull request by AsterDY**
resolve #258

### CODE REVIEW

**Review by chenzhuoyu — APPROVED** [review]

File: issue_test/issue258_test.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
+package issue_test
```
Comment (liuq19) [inline issue_test/issue258_test.go:1]: miss license
